language: python

addons:
  apt:
    packages:
    - nautilus
    - libglib2.0-bin

env:
  global:
    - TEST_DEPS="qtconsole notebook pytest"

matrix:
  include:
  - env: export PYTHON_VERSION=3.7
    python: 3.7
  - env: export PYTHON_VERSION=3.7; CONDA=true
  - env: export PYTHON_VERSION=3.6
    python: 3.6
  - env: export PYTHON_VERSION=3.6; CONDA=true


before_install:
  - mkdir -p ~/.local/share/nautilus/scripts/
  - |
    if [ $CONDA ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      chmod +x miniconda.sh
      ./miniconda.sh -b -p $HOME/miniconda
      hash -r
    fi

install:
  - |
    if [ $CONDA ]; then
      source $HOME/miniconda/bin/activate root
      conda update -yq conda
      conda create -n testenv --yes python=$PYTHON_VERSION
      source activate testenv
      conda install -y $TEST_DEPS
    else
      pip install $TEST_DEPS
    fi

  - pip install -e .

script:
  - pytest --pyargs start_jupyter_cm
  - start_jupyter_cm
  - ls ~/.local/share/nautilus/scripts
  - start_jupyter_cm --remove
  - gio --help