# environment variables
environment:

  global:
    TEST_DEPS: qtconsole notebook pytest

  matrix:
    - CONDA: true
      PYTHON_PATH: C:\\Miniconda37-x64
    - CONDA: false
      PYTHON_PATH: C:\\Python37

# scripts that run after cloning repository
install:
  - SET PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%
  - if "%CONDA%" == "true" conda create -y -n testenv
  - if "%CONDA%" == "true" activate testenv
  - if "%CONDA%" == "true" conda install -y %TEST_DEPS%
  - if "%CONDA%" == "false" pip install qtconsole notebook pytest

  # Install our package
  - 'pip install -e .'

build: off

test_script:
  - 'pytest --pyargs start_jupyter_cm'
  - 'jupyter_context-menu_add'
  - 'jupyter_context-menu_remove'

after_test:
  - 'python setup.py sdist bdist_wheel'

artifacts:
  - path: dist\*

