# environment variables
environment:

  global:
    TEST_DEPS: qtconsole notebook pytest

  matrix:
    - PYTHON_VERSION: 3.7
      CONDA: true
      PYTHON: C:\\Python37
    - PYTHON_VERSION: 3.7
      CONDA: false
      PYTHON: C:\\Python37

# scripts that run after cloning repository
install:
  - ps: |
      if ($env:CONDA -eq "true") {
        $env:PATH="C:\\Miniconda37-x64;C:\\Miniconda37-x64\\Scripts;$env:PATH"
        C:\\Miniconda37-x64\\Scripts\\activate.bat
        conda update -yq conda
        conda create -y -n testenv python=%env:PYTHON_VERSION
        conda install qtconsole notebook pytest
        activate testenv
      } else {
      $env:PATH="$env:PYTHON;$env:PYTHON\\Scripts;c:\python37\Scripts;$env:PATH"
      python -m pip install --upgrade pip
      pip install qtconsole notebook pytest
      }

  # Install our package
  - 'pip install -e .'

build: off

test_script:
  - 'pytest --pyargs start_jupyter_cm'

after_test:
  - 'python setup.py sdist bdist_wheel'

artifacts:
  - path: dist\*

